import { Injectable } from '@nestjs/common';
import { getSupabaseClient } from '../../config/supabase.config';
import { CreateHandoverDto, ConfirmHandoverDto } from './dto/handover.dto';
import { NotFoundException, ForbiddenException, ValidationException } from '../../common/exceptions/app.exception';

@Injectable()
export class HandoversService {
  private get supabase() {
    return getSupabaseClient();
  }

  async create(dto: CreateHandoverDto, userId: string) {
    // Verify user owns the lost_post
    const { data: lostPost } = await this.supabase
      .from('lost_posts').select('id, user_id').eq('id', dto.lost_post_id).single();

    if (!lostPost) throw new NotFoundException('Bài mất đồ', dto.lost_post_id);
    if (lostPost.user_id !== userId) throw new ForbiddenException('Bạn không phải chủ bài mất đồ này');

    const { data, error } = await this.supabase
      .from('handovers')
      .insert({
        ...dto,
        status: 'pending',
        // verification_code is auto-generated by DB DEFAULT
      })
      .select('*')
      .single();

    if (error) throw new ValidationException(error.message);
    return data;
  }

  async findOne(id: string) {
    const { data, error } = await this.supabase
      .from('handovers')
      .select(`
        *,
        lost_posts(id, title, users!lost_posts_user_id_fkey(full_name, email)),
        found_posts(id, title, users!found_posts_user_id_fkey(full_name, email)),
        storage_items(id, item_code, storage_locations(name))
      `)
      .eq('id', id)
      .single();

    if (error || !data) throw new NotFoundException('Handover', id);
    return data;
  }

  async confirmByOwner(id: string, dto: ConfirmHandoverDto, userId: string) {
    const handover = await this.findOne(id);

    if (handover.lost_posts.users.id !== userId) {
      // Check via user_id on lost post
    }

    if (handover.verification_code !== dto.verification_code) {
      throw new ValidationException('Mã xác thực không đúng');
    }
    if (new Date(handover.code_expires_at) < new Date()) {
      throw new ValidationException('Mã xác thực đã hết hạn');
    }

    const update: any = {
      confirmed_by_owner_id: userId,
      owner_confirmed_at: new Date().toISOString(),
      status: 'owner_confirmed',
    };

    if (handover.finder_confirmed_at) {
      update.status = 'completed';
      update.completed_at = new Date().toISOString();
    }

    const { data } = await this.supabase
      .from('handovers').update(update).eq('id', id).select('*').single();

    // Grant points if completed
    if (update.status === 'completed') {
      await this.grantPoints(id);
    }

    return data;
  }

  async confirmByFinder(id: string, dto: ConfirmHandoverDto, userId: string) {
    const handover = await this.findOne(id);

    if (handover.verification_code !== dto.verification_code) {
      throw new ValidationException('Mã xác thực không đúng');
    }
    if (new Date(handover.code_expires_at) < new Date()) {
      throw new ValidationException('Mã xác thực đã hết hạn');
    }

    const update: any = {
      confirmed_by_finder_id: userId,
      finder_confirmed_at: new Date().toISOString(),
      status: 'finder_confirmed',
    };

    if (handover.owner_confirmed_at) {
      update.status = 'completed';
      update.completed_at = new Date().toISOString();
    }

    const { data } = await this.supabase
      .from('handovers').update(update).eq('id', id).select('*').single();

    if (update.status === 'completed') {
      await this.grantPoints(id);
    }

    return data;
  }

  private async grantPoints(handoverId: string) {
    // Call the DB function
    await this.supabase.rpc('grant_training_points', { p_handover_id: handoverId });

    // Update lost_post & found_post status to 'closed'
    const { data: h } = await this.supabase
      .from('handovers').select('lost_post_id, found_post_id').eq('id', handoverId).single();

    if (h) {
      await Promise.all([
        this.supabase.from('lost_posts').update({ status: 'closed' }).eq('id', h.lost_post_id),
        this.supabase.from('found_posts').update({ status: 'closed' }).eq('id', h.found_post_id),
      ]);
    }
  }

  async getMyHandovers(userId: string) {
    const { data } = await this.supabase
      .from('handovers')
      .select(`
        id, status, verification_code, code_expires_at, points_awarded, created_at,
        lost_posts(id, title),
        found_posts(id, title)
      `)
      .or(`confirmed_by_owner_id.eq.${userId},confirmed_by_finder_id.eq.${userId}`)
      .order('created_at', { ascending: false });

    return data ?? [];
  }
}
